// Code generated by cmd/plugin-sdk; DO NOT EDIT.
export const protocol = "yotta.plugin/1" as const;
export const protoSHA256 = "04dfdae28e05e534da2443ffdc77dd193cfb2f2e79d9e52602cda831461d2cda" as const;
export type CanonicalJSON = Uint8Array & { readonly __canonicalJSON: unique symbol };
export type ValueEnvelope = CanonicalJSON & { readonly __valueEnvelope: unique symbol };
export interface NodeRef { nodeTypeId: string; version: string; semanticDigest: string }
export interface ImplementationLock { packageId: string; artifactDigest: string; abi: { kind: "process" | "wit"; version: "v1" }; entrypoint: string }
export interface Budget { maxFrameBytes: bigint; maxOutputBytes: bigint; maxHostCalls: number; maxStatusEvents: number }
export interface PortValue { portId: string; valueEnvelope: ValueEnvelope }
export interface Invocation { requestId: string; invocationId: string; graphId: string; nodeId: string; attempt: number; observedUnixMillis: bigint; deadlineUnixMillis: bigint; nodeRefJSON: CanonicalJSON; implementationLockJSON: CanonicalJSON; configJSON: CanonicalJSON; inputs: readonly PortValue[]; budget: Budget }
export type TerminationStrength = "cooperative" | "engine_interrupt" | "job_terminate" | "process_crash";
export interface Failure { code: string; output?: string; message: string }
