/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionTraceDrawer: typeof import('./src/components/ActionTraceDrawer.vue')['default']
    AlertBox: typeof import('./src/components/common/AlertBox.vue')['default']
    AppCard: typeof import('./src/components/common/AppCard.vue')['default']
    AppStatusBar: typeof import('./src/components/AppStatusBar.vue')['default']
    AppTitleBar: typeof import('./src/components/AppTitleBar.vue')['default']
    BaseModal: typeof import('./src/components/common/BaseModal.vue')['default']
    BotControls: typeof import('./src/components/BotControls.vue')['default']
    CappedPreviewImage: typeof import('./src/components/common/CappedPreviewImage.vue')['default']
    ComingSoonCard: typeof import('./src/components/ComingSoonCard.vue')['default']
    ConfirmDialog: typeof import('./src/components/common/ConfirmDialog.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    HotkeyCaptureInput: typeof import('./src/components/hotkeys/HotkeyCaptureInput.vue')['default']
    HudShell: typeof import('./src/components/tools/HudShell.vue')['default']
    HudStatePanel: typeof import('./src/components/tools/HudStatePanel.vue')['default']
    IconBadge: typeof import('./src/components/common/IconBadge.vue')['default']
    IconPicker: typeof import('./src/components/common/IconPicker.vue')['default']
    LauncherSurface: typeof import('./src/components/launcher/LauncherSurface.vue')['default']
    ListRow: typeof import('./src/components/common/ListRow.vue')['default']
    LogPanel: typeof import('./src/components/LogPanel.vue')['default']
    PickerMagnifier: typeof import('./src/components/tools/PickerMagnifier.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleEditorPanel: typeof import('./src/components/schedules/ScheduleEditorPanel.vue')['default']
    ScheduleListPanel: typeof import('./src/components/schedules/ScheduleListPanel.vue')['default']
    SectionHeader: typeof import('./src/components/common/SectionHeader.vue')['default']
    SettingsPageHeader: typeof import('./src/components/settings/SettingsPageHeader.vue')['default']
    SettingsRestartBadge: typeof import('./src/components/settings/SettingsRestartBadge.vue')['default']
    SettingsRow: typeof import('./src/components/settings/SettingsRow.vue')['default']
    SettingsSaveStatus: typeof import('./src/components/settings/SettingsSaveStatus.vue')['default']
    SettingsSection: typeof import('./src/components/settings/SettingsSection.vue')['default']
    SplitHandle: typeof import('./src/components/common/SplitHandle.vue')['default']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    StatusPill: typeof import('./src/components/common/StatusPill.vue')['default']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue')['default']
    UInputNumber: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    UKbd: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UPopover: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USeparator: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USkeleton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    USwitch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_a2c6100c66aa5f3ef89ec46e30405138/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
