/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionCard: typeof import('./src/components/actions/ActionCard.vue')['default']
    ActionEditorContent: typeof import('./src/components/actions/ActionEditorContent.vue')['default']
    ActionPicker: typeof import('./src/components/containers/ActionPicker.vue')['default']
    ActionRunningPill: typeof import('./src/components/actions/ActionRunningPill.vue')['default']
    ActionsFilterBar: typeof import('./src/components/actions/ActionsFilterBar.vue')['default']
    ActionsTab: typeof import('./src/components/tasks/ActionsTab.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AppStatusBar: typeof import('./src/components/AppStatusBar.vue')['default']
    AppTitleBar: typeof import('./src/components/AppTitleBar.vue')['default']
    BotControls: typeof import('./src/components/BotControls.vue')['default']
    ComingSoonCard: typeof import('./src/components/ComingSoonCard.vue')['default']
    ContainerFlowNode: typeof import('./src/components/containers/ContainerFlowNode.vue')['default']
    ContainerPropsPanel: typeof import('./src/components/containers/ContainerPropsPanel.vue')['default']
    ContainersTab: typeof import('./src/components/tasks/ContainersTab.vue')['default']
    EditorTitleBar: typeof import('./src/components/actions/EditorTitleBar.vue')['default']
    ExpressionInput: typeof import('./src/components/expressions/ExpressionInput.vue')['default']
    GameStatusIndicator: typeof import('./src/components/GameStatusIndicator.vue')['default']
    HotkeyCaptureInput: typeof import('./src/components/actions/HotkeyCaptureInput.vue')['default']
    KeyCapture: typeof import('./src/components/containers/KeyCapture.vue')['default']
    LogPanel: typeof import('./src/components/LogPanel.vue')['default']
    NodeInspector: typeof import('./src/components/containers/NodeInspector.vue')['default']
    NodePalette: typeof import('./src/components/containers/NodePalette.vue')['default']
    RecorderDialog: typeof import('./src/components/actions/RecorderDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleEditorPanel: typeof import('./src/components/schedules/ScheduleEditorPanel.vue')['default']
    ScheduleListPanel: typeof import('./src/components/schedules/ScheduleListPanel.vue')['default']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    StepClickEditor: typeof import('./src/components/actions/steps/StepClickEditor.vue')['default']
    StepKeyEditor: typeof import('./src/components/actions/steps/StepKeyEditor.vue')['default']
    StepMouseDragEditor: typeof import('./src/components/actions/steps/StepMouseDragEditor.vue')['default']
    StepMouseMoveEditor: typeof import('./src/components/actions/steps/StepMouseMoveEditor.vue')['default']
    StepMouseMoveRelEditor: typeof import('./src/components/actions/steps/StepMouseMoveRelEditor.vue')['default']
    StepRow: typeof import('./src/components/actions/StepRow.vue')['default']
    StepScrollEditor: typeof import('./src/components/actions/steps/StepScrollEditor.vue')['default']
    StepSleepEditor: typeof import('./src/components/actions/steps/StepSleepEditor.vue')['default']
    TemplateCapture: typeof import('./src/components/templates/TemplateCapture.vue')['default']
    TemplateManager: typeof import('./src/components/templates/TemplateManager.vue')['default']
    TemplatePicker: typeof import('./src/components/containers/TemplatePicker.vue')['default']
    TemplatesTab: typeof import('./src/components/tasks/TemplatesTab.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputNumber: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UPopover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USlider: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Slider.vue')['default']
    USwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTabs: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
