allowBuilds:
  esbuild: true
  vue-demi: true
overrides:
  '@apidevtools/json-schema-ref-parser>js-yaml': 4.3.1
  fontless>esbuild: 0.28.2
  json-schema-to-typescript>js-yaml: 4.3.1
  markdown-it>linkify-it: 5.0.2
