// Code generated by cmd/plugin-sdk; DO NOT EDIT.

package pluginsdk

import "github.com/yottaapp/yotta/internal/pluginprotocol"

const (
	Protocol             = pluginprotocol.Protocol
	ProcessGuestArgument = "--yotta-plugin-process-v1"
	ProtoSHA256          = "04dfdae28e05e534da2443ffdc77dd193cfb2f2e79d9e52602cda831461d2cda"
)

type Invocation = pluginprotocol.Invocation
type PortValue = pluginprotocol.PortValue
type Trigger = pluginprotocol.Trigger
type Budget = pluginprotocol.Budget
type Counter = pluginprotocol.Counter
type Fact = pluginprotocol.Fact
type Failure = pluginprotocol.Failure
type Action = pluginprotocol.ActionEvent
type HostOpenResponse = pluginprotocol.HostOpenResponse
type HostInvokeResponse = pluginprotocol.HostInvokeResponse
type HostDropResponse = pluginprotocol.HostDropResponse
type HostEntropyResponse = pluginprotocol.HostEntropyResponse
type HostWaitResponse = pluginprotocol.HostWaitResponse
type StateReadResponse = pluginprotocol.StateReadResponse
type StateWriteResponse = pluginprotocol.StateWriteResponse
