// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: contracts/plugin/v1/plugin.proto

package pluginprotocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Outcome int32

const (
	Outcome_OUTCOME_UNSPECIFIED Outcome = 0
	Outcome_OUTCOME_SUCCEEDED   Outcome = 1
	Outcome_OUTCOME_FAILED      Outcome = 2
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_SUCCEEDED",
		2: "OUTCOME_FAILED",
	}
	Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"OUTCOME_SUCCEEDED":   1,
		"OUTCOME_FAILED":      2,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_contracts_plugin_v1_plugin_proto_enumTypes[0]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type Frame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Protocol string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Sequence uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Frame_Invocation
	//	*Frame_HostOpenRequest
	//	*Frame_HostOpenResponse
	//	*Frame_HostInvokeRequest
	//	*Frame_HostInvokeResponse
	//	*Frame_HostDropRequest
	//	*Frame_HostDropResponse
	//	*Frame_Status
	//	*Frame_Result
	//	*Frame_Cancel
	//	*Frame_HostEntropyRequest
	//	*Frame_HostEntropyResponse
	//	*Frame_HostWaitRequest
	//	*Frame_HostWaitResponse
	//	*Frame_StateReadRequest
	//	*Frame_StateReadResponse
	//	*Frame_StateWriteRequest
	//	*Frame_StateWriteResponse
	//	*Frame_Action
	Payload       isFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Frame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Frame) GetPayload() isFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetInvocation() *Invocation {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Invocation); ok {
			return x.Invocation
		}
	}
	return nil
}

func (x *Frame) GetHostOpenRequest() *HostOpenRequest {
	if x != nil {
		if x, ok := x.Payload.(*Frame_HostOpenRequest); ok {
			return x.HostOpenRequest
		}
	}
	return nil
}

func (x *Frame) GetHostOpenResponse() *HostOpenResponse {
	if x != nil {
		if x, ok := x.Payload.(*Frame_HostOpenResponse); ok {
			return x.HostOpenResponse
		}
	}
	return nil
}

func (x *Frame) GetHostInvokeRequest() *HostInvokeRequest {
	if x != nil {
		if x, ok := x.Payload.(*Frame_HostInvokeRequest); ok {
			return x.HostInvokeRequest
		}
	}
	return nil
}

func (x *Frame) GetHostInvokeResponse() *HostInvokeResponse {
	if x != nil {
		if x, ok := x.Payload.(*Frame_HostInvokeResponse); ok {
			return x.HostInvokeResponse
		}
	}
	return nil
}

func (x *Frame) GetHostDropRequest() *HostDropRequest {
	if x != nil {
		if x, ok := x.Payload.(*Frame_HostDropRequest); ok {
			return x.HostDropRequest
		}
	}
	return nil
}

func (x *Frame) GetHostDropResponse() *HostDropResponse {
	if x != nil {
		if x, ok := x.Payload.(*Frame_HostDropResponse); ok {
			return x.HostDropResponse
		}
	}
	return nil
}

func (x *Frame) GetStatus() *StatusEvent {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *Frame) GetResult() *Result {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *Frame) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *Frame) GetHostEntropyRequest() *HostEntropyRequest {
	if x != nil {
		if x, ok := x.Payload.(*Frame_HostEntropyRequest); ok {
			return x.HostEntropyRequest
		}
	}
	return nil
}

func (x *Frame) GetHostEntropyResponse() *HostEntropyResponse {
	if x != nil {
		if x, ok := x.Payload.(*Frame_HostEntropyResponse); ok {
			return x.HostEntropyResponse
		}
	}
	return nil
}

func (x *Frame) GetHostWaitRequest() *HostWaitRequest {
	if x != nil {
		if x, ok := x.Payload.(*Frame_HostWaitRequest); ok {
			return x.HostWaitRequest
		}
	}
	return nil
}

func (x *Frame) GetHostWaitResponse() *HostWaitResponse {
	if x != nil {
		if x, ok := x.Payload.(*Frame_HostWaitResponse); ok {
			return x.HostWaitResponse
		}
	}
	return nil
}

func (x *Frame) GetStateReadRequest() *StateReadRequest {
	if x != nil {
		if x, ok := x.Payload.(*Frame_StateReadRequest); ok {
			return x.StateReadRequest
		}
	}
	return nil
}

func (x *Frame) GetStateReadResponse() *StateReadResponse {
	if x != nil {
		if x, ok := x.Payload.(*Frame_StateReadResponse); ok {
			return x.StateReadResponse
		}
	}
	return nil
}

func (x *Frame) GetStateWriteRequest() *StateWriteRequest {
	if x != nil {
		if x, ok := x.Payload.(*Frame_StateWriteRequest); ok {
			return x.StateWriteRequest
		}
	}
	return nil
}

func (x *Frame) GetStateWriteResponse() *StateWriteResponse {
	if x != nil {
		if x, ok := x.Payload.(*Frame_StateWriteResponse); ok {
			return x.StateWriteResponse
		}
	}
	return nil
}

func (x *Frame) GetAction() *ActionEvent {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Action); ok {
			return x.Action
		}
	}
	return nil
}

type isFrame_Payload interface {
	isFrame_Payload()
}

type Frame_Invocation struct {
	Invocation *Invocation `protobuf:"bytes,10,opt,name=invocation,proto3,oneof"`
}

type Frame_HostOpenRequest struct {
	HostOpenRequest *HostOpenRequest `protobuf:"bytes,11,opt,name=host_open_request,json=hostOpenRequest,proto3,oneof"`
}

type Frame_HostOpenResponse struct {
	HostOpenResponse *HostOpenResponse `protobuf:"bytes,12,opt,name=host_open_response,json=hostOpenResponse,proto3,oneof"`
}

type Frame_HostInvokeRequest struct {
	HostInvokeRequest *HostInvokeRequest `protobuf:"bytes,13,opt,name=host_invoke_request,json=hostInvokeRequest,proto3,oneof"`
}

type Frame_HostInvokeResponse struct {
	HostInvokeResponse *HostInvokeResponse `protobuf:"bytes,14,opt,name=host_invoke_response,json=hostInvokeResponse,proto3,oneof"`
}

type Frame_HostDropRequest struct {
	HostDropRequest *HostDropRequest `protobuf:"bytes,15,opt,name=host_drop_request,json=hostDropRequest,proto3,oneof"`
}

type Frame_HostDropResponse struct {
	HostDropResponse *HostDropResponse `protobuf:"bytes,16,opt,name=host_drop_response,json=hostDropResponse,proto3,oneof"`
}

type Frame_Status struct {
	Status *StatusEvent `protobuf:"bytes,17,opt,name=status,proto3,oneof"`
}

type Frame_Result struct {
	Result *Result `protobuf:"bytes,18,opt,name=result,proto3,oneof"`
}

type Frame_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,19,opt,name=cancel,proto3,oneof"`
}

type Frame_HostEntropyRequest struct {
	HostEntropyRequest *HostEntropyRequest `protobuf:"bytes,20,opt,name=host_entropy_request,json=hostEntropyRequest,proto3,oneof"`
}

type Frame_HostEntropyResponse struct {
	HostEntropyResponse *HostEntropyResponse `protobuf:"bytes,21,opt,name=host_entropy_response,json=hostEntropyResponse,proto3,oneof"`
}

type Frame_HostWaitRequest struct {
	HostWaitRequest *HostWaitRequest `protobuf:"bytes,22,opt,name=host_wait_request,json=hostWaitRequest,proto3,oneof"`
}

type Frame_HostWaitResponse struct {
	HostWaitResponse *HostWaitResponse `protobuf:"bytes,23,opt,name=host_wait_response,json=hostWaitResponse,proto3,oneof"`
}

type Frame_StateReadRequest struct {
	StateReadRequest *StateReadRequest `protobuf:"bytes,24,opt,name=state_read_request,json=stateReadRequest,proto3,oneof"`
}

type Frame_StateReadResponse struct {
	StateReadResponse *StateReadResponse `protobuf:"bytes,25,opt,name=state_read_response,json=stateReadResponse,proto3,oneof"`
}

type Frame_StateWriteRequest struct {
	StateWriteRequest *StateWriteRequest `protobuf:"bytes,26,opt,name=state_write_request,json=stateWriteRequest,proto3,oneof"`
}

type Frame_StateWriteResponse struct {
	StateWriteResponse *StateWriteResponse `protobuf:"bytes,27,opt,name=state_write_response,json=stateWriteResponse,proto3,oneof"`
}

type Frame_Action struct {
	Action *ActionEvent `protobuf:"bytes,28,opt,name=action,proto3,oneof"`
}

func (*Frame_Invocation) isFrame_Payload() {}

func (*Frame_HostOpenRequest) isFrame_Payload() {}

func (*Frame_HostOpenResponse) isFrame_Payload() {}

func (*Frame_HostInvokeRequest) isFrame_Payload() {}

func (*Frame_HostInvokeResponse) isFrame_Payload() {}

func (*Frame_HostDropRequest) isFrame_Payload() {}

func (*Frame_HostDropResponse) isFrame_Payload() {}

func (*Frame_Status) isFrame_Payload() {}

func (*Frame_Result) isFrame_Payload() {}

func (*Frame_Cancel) isFrame_Payload() {}

func (*Frame_HostEntropyRequest) isFrame_Payload() {}

func (*Frame_HostEntropyResponse) isFrame_Payload() {}

func (*Frame_HostWaitRequest) isFrame_Payload() {}

func (*Frame_HostWaitResponse) isFrame_Payload() {}

func (*Frame_StateReadRequest) isFrame_Payload() {}

func (*Frame_StateReadResponse) isFrame_Payload() {}

func (*Frame_StateWriteRequest) isFrame_Payload() {}

func (*Frame_StateWriteResponse) isFrame_Payload() {}

func (*Frame_Action) isFrame_Payload() {}

type Invocation struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	RequestId              string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	InvocationId           string                 `protobuf:"bytes,2,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	GraphId                string                 `protobuf:"bytes,3,opt,name=graph_id,json=graphId,proto3" json:"graph_id,omitempty"`
	NodeId                 string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Attempt                uint32                 `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	ObservedUnixMillis     int64                  `protobuf:"varint,6,opt,name=observed_unix_millis,json=observedUnixMillis,proto3" json:"observed_unix_millis,omitempty"`
	DeadlineUnixMillis     int64                  `protobuf:"varint,7,opt,name=deadline_unix_millis,json=deadlineUnixMillis,proto3" json:"deadline_unix_millis,omitempty"`
	NodeRefJson            []byte                 `protobuf:"bytes,8,opt,name=node_ref_json,json=nodeRefJson,proto3" json:"node_ref_json,omitempty"`
	ImplementationLockJson []byte                 `protobuf:"bytes,9,opt,name=implementation_lock_json,json=implementationLockJson,proto3" json:"implementation_lock_json,omitempty"`
	ConfigJson             []byte                 `protobuf:"bytes,10,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	Inputs                 []*PortValue           `protobuf:"bytes,11,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Trigger                *Trigger               `protobuf:"bytes,12,opt,name=trigger,proto3" json:"trigger,omitempty"`
	Budget                 *Budget                `protobuf:"bytes,13,opt,name=budget,proto3" json:"budget,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Invocation) Reset() {
	*x = Invocation{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invocation) ProtoMessage() {}

func (x *Invocation) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invocation.ProtoReflect.Descriptor instead.
func (*Invocation) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *Invocation) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Invocation) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *Invocation) GetGraphId() string {
	if x != nil {
		return x.GraphId
	}
	return ""
}

func (x *Invocation) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Invocation) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Invocation) GetObservedUnixMillis() int64 {
	if x != nil {
		return x.ObservedUnixMillis
	}
	return 0
}

func (x *Invocation) GetDeadlineUnixMillis() int64 {
	if x != nil {
		return x.DeadlineUnixMillis
	}
	return 0
}

func (x *Invocation) GetNodeRefJson() []byte {
	if x != nil {
		return x.NodeRefJson
	}
	return nil
}

func (x *Invocation) GetImplementationLockJson() []byte {
	if x != nil {
		return x.ImplementationLockJson
	}
	return nil
}

func (x *Invocation) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *Invocation) GetInputs() []*PortValue {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Invocation) GetTrigger() *Trigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *Invocation) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

type PortValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortId        string                 `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	ValueEnvelope []byte                 `protobuf:"bytes,2,opt,name=value_envelope,json=valueEnvelope,proto3" json:"value_envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortValue) Reset() {
	*x = PortValue{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortValue) ProtoMessage() {}

func (x *PortValue) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortValue.ProtoReflect.Descriptor instead.
func (*PortValue) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PortValue) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *PortValue) GetValueEnvelope() []byte {
	if x != nil {
		return x.ValueEnvelope
	}
	return nil
}

type Trigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	InputPort     string                 `protobuf:"bytes,2,opt,name=input_port,json=inputPort,proto3" json:"input_port,omitempty"`
	SourceNodeId  string                 `protobuf:"bytes,3,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	SourcePortId  string                 `protobuf:"bytes,4,opt,name=source_port_id,json=sourcePortId,proto3" json:"source_port_id,omitempty"`
	FailureJson   []byte                 `protobuf:"bytes,5,opt,name=failure_json,json=failureJson,proto3" json:"failure_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trigger) Reset() {
	*x = Trigger{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger) ProtoMessage() {}

func (x *Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trigger.ProtoReflect.Descriptor instead.
func (*Trigger) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Trigger) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Trigger) GetInputPort() string {
	if x != nil {
		return x.InputPort
	}
	return ""
}

func (x *Trigger) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *Trigger) GetSourcePortId() string {
	if x != nil {
		return x.SourcePortId
	}
	return ""
}

func (x *Trigger) GetFailureJson() []byte {
	if x != nil {
		return x.FailureJson
	}
	return nil
}

type Budget struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxFrameBytes   uint64                 `protobuf:"varint,1,opt,name=max_frame_bytes,json=maxFrameBytes,proto3" json:"max_frame_bytes,omitempty"`
	MaxOutputBytes  uint64                 `protobuf:"varint,2,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	MaxHostCalls    uint32                 `protobuf:"varint,3,opt,name=max_host_calls,json=maxHostCalls,proto3" json:"max_host_calls,omitempty"`
	MaxStatusEvents uint32                 `protobuf:"varint,4,opt,name=max_status_events,json=maxStatusEvents,proto3" json:"max_status_events,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Budget) Reset() {
	*x = Budget{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Budget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budget) ProtoMessage() {}

func (x *Budget) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budget.ProtoReflect.Descriptor instead.
func (*Budget) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Budget) GetMaxFrameBytes() uint64 {
	if x != nil {
		return x.MaxFrameBytes
	}
	return 0
}

func (x *Budget) GetMaxOutputBytes() uint64 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

func (x *Budget) GetMaxHostCalls() uint32 {
	if x != nil {
		return x.MaxHostCalls
	}
	return 0
}

func (x *Budget) GetMaxStatusEvents() uint32 {
	if x != nil {
		return x.MaxStatusEvents
	}
	return 0
}

type HostOpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RequirementId string                 `protobuf:"bytes,2,opt,name=requirement_id,json=requirementId,proto3" json:"requirement_id,omitempty"`
	Operations    []string               `protobuf:"bytes,3,rep,name=operations,proto3" json:"operations,omitempty"`
	ConfigJson    []byte                 `protobuf:"bytes,4,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostOpenRequest) Reset() {
	*x = HostOpenRequest{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostOpenRequest) ProtoMessage() {}

func (x *HostOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostOpenRequest.ProtoReflect.Descriptor instead.
func (*HostOpenRequest) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *HostOpenRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HostOpenRequest) GetRequirementId() string {
	if x != nil {
		return x.RequirementId
	}
	return ""
}

func (x *HostOpenRequest) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *HostOpenRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type HostOpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	HandleJson    []byte                 `protobuf:"bytes,2,opt,name=handle_json,json=handleJson,proto3" json:"handle_json,omitempty"`
	Failure       *Failure               `protobuf:"bytes,3,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostOpenResponse) Reset() {
	*x = HostOpenResponse{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostOpenResponse) ProtoMessage() {}

func (x *HostOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostOpenResponse.ProtoReflect.Descriptor instead.
func (*HostOpenResponse) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *HostOpenResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HostOpenResponse) GetHandleJson() []byte {
	if x != nil {
		return x.HandleJson
	}
	return nil
}

func (x *HostOpenResponse) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type HostInvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RequirementId string                 `protobuf:"bytes,2,opt,name=requirement_id,json=requirementId,proto3" json:"requirement_id,omitempty"`
	HandleJson    []byte                 `protobuf:"bytes,3,opt,name=handle_json,json=handleJson,proto3" json:"handle_json,omitempty"`
	Operation     string                 `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInvokeRequest) Reset() {
	*x = HostInvokeRequest{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInvokeRequest) ProtoMessage() {}

func (x *HostInvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInvokeRequest.ProtoReflect.Descriptor instead.
func (*HostInvokeRequest) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *HostInvokeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HostInvokeRequest) GetRequirementId() string {
	if x != nil {
		return x.RequirementId
	}
	return ""
}

func (x *HostInvokeRequest) GetHandleJson() []byte {
	if x != nil {
		return x.HandleJson
	}
	return nil
}

func (x *HostInvokeRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *HostInvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HostInvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Failure       *Failure               `protobuf:"bytes,3,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInvokeResponse) Reset() {
	*x = HostInvokeResponse{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInvokeResponse) ProtoMessage() {}

func (x *HostInvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInvokeResponse.ProtoReflect.Descriptor instead.
func (*HostInvokeResponse) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *HostInvokeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HostInvokeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HostInvokeResponse) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type HostDropRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RequirementId string                 `protobuf:"bytes,2,opt,name=requirement_id,json=requirementId,proto3" json:"requirement_id,omitempty"`
	HandleJson    []byte                 `protobuf:"bytes,3,opt,name=handle_json,json=handleJson,proto3" json:"handle_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostDropRequest) Reset() {
	*x = HostDropRequest{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostDropRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostDropRequest) ProtoMessage() {}

func (x *HostDropRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostDropRequest.ProtoReflect.Descriptor instead.
func (*HostDropRequest) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *HostDropRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HostDropRequest) GetRequirementId() string {
	if x != nil {
		return x.RequirementId
	}
	return ""
}

func (x *HostDropRequest) GetHandleJson() []byte {
	if x != nil {
		return x.HandleJson
	}
	return nil
}

type HostDropResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Failure       *Failure               `protobuf:"bytes,2,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostDropResponse) Reset() {
	*x = HostDropResponse{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostDropResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostDropResponse) ProtoMessage() {}

func (x *HostDropResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostDropResponse.ProtoReflect.Descriptor instead.
func (*HostDropResponse) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *HostDropResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HostDropResponse) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type StatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Counters      []*Counter             `protobuf:"bytes,2,rep,name=counters,proto3" json:"counters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *StatusEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StatusEvent) GetCounters() []*Counter {
	if x != nil {
		return x.Counters
	}
	return nil
}

type Counter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Counter) Reset() {
	*x = Counter{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counter) ProtoMessage() {}

func (x *Counter) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counter.ProtoReflect.Descriptor instead.
func (*Counter) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *Counter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Counter) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Result struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Outcome             Outcome                `protobuf:"varint,1,opt,name=outcome,proto3,enum=yotta.plugin.v1.Outcome" json:"outcome,omitempty"`
	Outputs             []*PortValue           `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	ExecOutputs         []string               `protobuf:"bytes,3,rep,name=exec_outputs,json=execOutputs,proto3" json:"exec_outputs,omitempty"`
	Failure             *Failure               `protobuf:"bytes,4,opt,name=failure,proto3" json:"failure,omitempty"`
	TerminationStrength string                 `protobuf:"bytes,5,opt,name=termination_strength,json=terminationStrength,proto3" json:"termination_strength,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *Result) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *Result) GetOutputs() []*PortValue {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Result) GetExecOutputs() []string {
	if x != nil {
		return x.ExecOutputs
	}
	return nil
}

func (x *Result) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *Result) GetTerminationStrength() string {
	if x != nil {
		return x.TerminationStrength
	}
	return ""
}

type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *Failure) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Failure) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Failure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *Cancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type HostEntropyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ByteCount     uint32                 `protobuf:"varint,2,opt,name=byte_count,json=byteCount,proto3" json:"byte_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostEntropyRequest) Reset() {
	*x = HostEntropyRequest{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostEntropyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostEntropyRequest) ProtoMessage() {}

func (x *HostEntropyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostEntropyRequest.ProtoReflect.Descriptor instead.
func (*HostEntropyRequest) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *HostEntropyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HostEntropyRequest) GetByteCount() uint32 {
	if x != nil {
		return x.ByteCount
	}
	return 0
}

type HostEntropyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Entropy       []byte                 `protobuf:"bytes,2,opt,name=entropy,proto3" json:"entropy,omitempty"`
	Failure       *Failure               `protobuf:"bytes,3,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostEntropyResponse) Reset() {
	*x = HostEntropyResponse{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostEntropyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostEntropyResponse) ProtoMessage() {}

func (x *HostEntropyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostEntropyResponse.ProtoReflect.Descriptor instead.
func (*HostEntropyResponse) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *HostEntropyResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HostEntropyResponse) GetEntropy() []byte {
	if x != nil {
		return x.Entropy
	}
	return nil
}

func (x *HostEntropyResponse) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type HostWaitRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DurationMillis uint64                 `protobuf:"varint,2,opt,name=duration_millis,json=durationMillis,proto3" json:"duration_millis,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HostWaitRequest) Reset() {
	*x = HostWaitRequest{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostWaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostWaitRequest) ProtoMessage() {}

func (x *HostWaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostWaitRequest.ProtoReflect.Descriptor instead.
func (*HostWaitRequest) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *HostWaitRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HostWaitRequest) GetDurationMillis() uint64 {
	if x != nil {
		return x.DurationMillis
	}
	return 0
}

type HostWaitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Failure       *Failure               `protobuf:"bytes,2,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostWaitResponse) Reset() {
	*x = HostWaitResponse{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostWaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostWaitResponse) ProtoMessage() {}

func (x *HostWaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostWaitResponse.ProtoReflect.Descriptor instead.
func (*HostWaitResponse) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *HostWaitResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HostWaitResponse) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type StateReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AccessId      string                 `protobuf:"bytes,2,opt,name=access_id,json=accessId,proto3" json:"access_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateReadRequest) Reset() {
	*x = StateReadRequest{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateReadRequest) ProtoMessage() {}

func (x *StateReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateReadRequest.ProtoReflect.Descriptor instead.
func (*StateReadRequest) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *StateReadRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StateReadRequest) GetAccessId() string {
	if x != nil {
		return x.AccessId
	}
	return ""
}

type StateReadResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ValueEnvelope     []byte                 `protobuf:"bytes,2,opt,name=value_envelope,json=valueEnvelope,proto3" json:"value_envelope,omitempty"`
	Revision          int64                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	ChangedUnixMillis int64                  `protobuf:"varint,4,opt,name=changed_unix_millis,json=changedUnixMillis,proto3" json:"changed_unix_millis,omitempty"`
	Failure           *Failure               `protobuf:"bytes,5,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StateReadResponse) Reset() {
	*x = StateReadResponse{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateReadResponse) ProtoMessage() {}

func (x *StateReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateReadResponse.ProtoReflect.Descriptor instead.
func (*StateReadResponse) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *StateReadResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StateReadResponse) GetValueEnvelope() []byte {
	if x != nil {
		return x.ValueEnvelope
	}
	return nil
}

func (x *StateReadResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *StateReadResponse) GetChangedUnixMillis() int64 {
	if x != nil {
		return x.ChangedUnixMillis
	}
	return 0
}

func (x *StateReadResponse) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type StateWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AccessId      string                 `protobuf:"bytes,2,opt,name=access_id,json=accessId,proto3" json:"access_id,omitempty"`
	ValueEnvelope []byte                 `protobuf:"bytes,3,opt,name=value_envelope,json=valueEnvelope,proto3" json:"value_envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateWriteRequest) Reset() {
	*x = StateWriteRequest{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateWriteRequest) ProtoMessage() {}

func (x *StateWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateWriteRequest.ProtoReflect.Descriptor instead.
func (*StateWriteRequest) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *StateWriteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StateWriteRequest) GetAccessId() string {
	if x != nil {
		return x.AccessId
	}
	return ""
}

func (x *StateWriteRequest) GetValueEnvelope() []byte {
	if x != nil {
		return x.ValueEnvelope
	}
	return nil
}

type StateWriteResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ValueEnvelope     []byte                 `protobuf:"bytes,2,opt,name=value_envelope,json=valueEnvelope,proto3" json:"value_envelope,omitempty"`
	Revision          int64                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	ChangedUnixMillis int64                  `protobuf:"varint,4,opt,name=changed_unix_millis,json=changedUnixMillis,proto3" json:"changed_unix_millis,omitempty"`
	Failure           *Failure               `protobuf:"bytes,5,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StateWriteResponse) Reset() {
	*x = StateWriteResponse{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateWriteResponse) ProtoMessage() {}

func (x *StateWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateWriteResponse.ProtoReflect.Descriptor instead.
func (*StateWriteResponse) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *StateWriteResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StateWriteResponse) GetValueEnvelope() []byte {
	if x != nil {
		return x.ValueEnvelope
	}
	return nil
}

func (x *StateWriteResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *StateWriteResponse) GetChangedUnixMillis() int64 {
	if x != nil {
		return x.ChangedUnixMillis
	}
	return 0
}

func (x *StateWriteResponse) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type ActionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EffectId      string                 `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Outcome       string                 `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	SummaryCode   string                 `protobuf:"bytes,5,opt,name=summary_code,json=summaryCode,proto3" json:"summary_code,omitempty"`
	Counters      []*Counter             `protobuf:"bytes,6,rep,name=counters,proto3" json:"counters,omitempty"`
	Facts         []*Fact                `protobuf:"bytes,7,rep,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionEvent) Reset() {
	*x = ActionEvent{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionEvent) ProtoMessage() {}

func (x *ActionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionEvent.ProtoReflect.Descriptor instead.
func (*ActionEvent) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *ActionEvent) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *ActionEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActionEvent) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *ActionEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ActionEvent) GetSummaryCode() string {
	if x != nil {
		return x.SummaryCode
	}
	return ""
}

func (x *ActionEvent) GetCounters() []*Counter {
	if x != nil {
		return x.Counters
	}
	return nil
}

func (x *ActionEvent) GetFacts() []*Fact {
	if x != nil {
		return x.Facts
	}
	return nil
}

type Fact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fact) Reset() {
	*x = Fact{}
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fact) ProtoMessage() {}

func (x *Fact) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_plugin_v1_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fact.ProtoReflect.Descriptor instead.
func (*Fact) Descriptor() ([]byte, []int) {
	return file_contracts_plugin_v1_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *Fact) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Fact) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_contracts_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_contracts_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	" contracts/plugin/v1/plugin.proto\x12\x0fyotta.plugin.v1\"\x84\f\n" +
	"\x05Frame\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12=\n" +
	"\n" +
	"invocation\x18\n" +
	" \x01(\v2\x1b.yotta.plugin.v1.InvocationH\x00R\n" +
	"invocation\x12N\n" +
	"\x11host_open_request\x18\v \x01(\v2 .yotta.plugin.v1.HostOpenRequestH\x00R\x0fhostOpenRequest\x12Q\n" +
	"\x12host_open_response\x18\f \x01(\v2!.yotta.plugin.v1.HostOpenResponseH\x00R\x10hostOpenResponse\x12T\n" +
	"\x13host_invoke_request\x18\r \x01(\v2\".yotta.plugin.v1.HostInvokeRequestH\x00R\x11hostInvokeRequest\x12W\n" +
	"\x14host_invoke_response\x18\x0e \x01(\v2#.yotta.plugin.v1.HostInvokeResponseH\x00R\x12hostInvokeResponse\x12N\n" +
	"\x11host_drop_request\x18\x0f \x01(\v2 .yotta.plugin.v1.HostDropRequestH\x00R\x0fhostDropRequest\x12Q\n" +
	"\x12host_drop_response\x18\x10 \x01(\v2!.yotta.plugin.v1.HostDropResponseH\x00R\x10hostDropResponse\x126\n" +
	"\x06status\x18\x11 \x01(\v2\x1c.yotta.plugin.v1.StatusEventH\x00R\x06status\x121\n" +
	"\x06result\x18\x12 \x01(\v2\x17.yotta.plugin.v1.ResultH\x00R\x06result\x121\n" +
	"\x06cancel\x18\x13 \x01(\v2\x17.yotta.plugin.v1.CancelH\x00R\x06cancel\x12W\n" +
	"\x14host_entropy_request\x18\x14 \x01(\v2#.yotta.plugin.v1.HostEntropyRequestH\x00R\x12hostEntropyRequest\x12Z\n" +
	"\x15host_entropy_response\x18\x15 \x01(\v2$.yotta.plugin.v1.HostEntropyResponseH\x00R\x13hostEntropyResponse\x12N\n" +
	"\x11host_wait_request\x18\x16 \x01(\v2 .yotta.plugin.v1.HostWaitRequestH\x00R\x0fhostWaitRequest\x12Q\n" +
	"\x12host_wait_response\x18\x17 \x01(\v2!.yotta.plugin.v1.HostWaitResponseH\x00R\x10hostWaitResponse\x12Q\n" +
	"\x12state_read_request\x18\x18 \x01(\v2!.yotta.plugin.v1.StateReadRequestH\x00R\x10stateReadRequest\x12T\n" +
	"\x13state_read_response\x18\x19 \x01(\v2\".yotta.plugin.v1.StateReadResponseH\x00R\x11stateReadResponse\x12T\n" +
	"\x13state_write_request\x18\x1a \x01(\v2\".yotta.plugin.v1.StateWriteRequestH\x00R\x11stateWriteRequest\x12W\n" +
	"\x14state_write_response\x18\x1b \x01(\v2#.yotta.plugin.v1.StateWriteResponseH\x00R\x12stateWriteResponse\x126\n" +
	"\x06action\x18\x1c \x01(\v2\x1c.yotta.plugin.v1.ActionEventH\x00R\x06actionB\t\n" +
	"\apayload\"\x9a\x04\n" +
	"\n" +
	"Invocation\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rinvocation_id\x18\x02 \x01(\tR\finvocationId\x12\x19\n" +
	"\bgraph_id\x18\x03 \x01(\tR\agraphId\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\rR\aattempt\x120\n" +
	"\x14observed_unix_millis\x18\x06 \x01(\x03R\x12observedUnixMillis\x120\n" +
	"\x14deadline_unix_millis\x18\a \x01(\x03R\x12deadlineUnixMillis\x12\"\n" +
	"\rnode_ref_json\x18\b \x01(\fR\vnodeRefJson\x128\n" +
	"\x18implementation_lock_json\x18\t \x01(\fR\x16implementationLockJson\x12\x1f\n" +
	"\vconfig_json\x18\n" +
	" \x01(\fR\n" +
	"configJson\x122\n" +
	"\x06inputs\x18\v \x03(\v2\x1a.yotta.plugin.v1.PortValueR\x06inputs\x122\n" +
	"\atrigger\x18\f \x01(\v2\x18.yotta.plugin.v1.TriggerR\atrigger\x12/\n" +
	"\x06budget\x18\r \x01(\v2\x17.yotta.plugin.v1.BudgetR\x06budget\"K\n" +
	"\tPortValue\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12%\n" +
	"\x0evalue_envelope\x18\x02 \x01(\fR\rvalueEnvelope\"\xb1\x01\n" +
	"\aTrigger\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"input_port\x18\x02 \x01(\tR\tinputPort\x12$\n" +
	"\x0esource_node_id\x18\x03 \x01(\tR\fsourceNodeId\x12$\n" +
	"\x0esource_port_id\x18\x04 \x01(\tR\fsourcePortId\x12!\n" +
	"\ffailure_json\x18\x05 \x01(\fR\vfailureJson\"\xac\x01\n" +
	"\x06Budget\x12&\n" +
	"\x0fmax_frame_bytes\x18\x01 \x01(\x04R\rmaxFrameBytes\x12(\n" +
	"\x10max_output_bytes\x18\x02 \x01(\x04R\x0emaxOutputBytes\x12$\n" +
	"\x0emax_host_calls\x18\x03 \x01(\rR\fmaxHostCalls\x12*\n" +
	"\x11max_status_events\x18\x04 \x01(\rR\x0fmaxStatusEvents\"\x98\x01\n" +
	"\x0fHostOpenRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0erequirement_id\x18\x02 \x01(\tR\rrequirementId\x12\x1e\n" +
	"\n" +
	"operations\x18\x03 \x03(\tR\n" +
	"operations\x12\x1f\n" +
	"\vconfig_json\x18\x04 \x01(\fR\n" +
	"configJson\"\x86\x01\n" +
	"\x10HostOpenResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vhandle_json\x18\x02 \x01(\fR\n" +
	"handleJson\x122\n" +
	"\afailure\x18\x03 \x01(\v2\x18.yotta.plugin.v1.FailureR\afailure\"\xb2\x01\n" +
	"\x11HostInvokeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0erequirement_id\x18\x02 \x01(\tR\rrequirementId\x12\x1f\n" +
	"\vhandle_json\x18\x03 \x01(\fR\n" +
	"handleJson\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\x81\x01\n" +
	"\x12HostInvokeResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x122\n" +
	"\afailure\x18\x03 \x01(\v2\x18.yotta.plugin.v1.FailureR\afailure\"x\n" +
	"\x0fHostDropRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0erequirement_id\x18\x02 \x01(\tR\rrequirementId\x12\x1f\n" +
	"\vhandle_json\x18\x03 \x01(\fR\n" +
	"handleJson\"e\n" +
	"\x10HostDropResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x122\n" +
	"\afailure\x18\x02 \x01(\v2\x18.yotta.plugin.v1.FailureR\afailure\"W\n" +
	"\vStatusEvent\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x124\n" +
	"\bcounters\x18\x02 \x03(\v2\x18.yotta.plugin.v1.CounterR\bcounters\"1\n" +
	"\aCounter\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"\xfc\x01\n" +
	"\x06Result\x122\n" +
	"\aoutcome\x18\x01 \x01(\x0e2\x18.yotta.plugin.v1.OutcomeR\aoutcome\x124\n" +
	"\aoutputs\x18\x02 \x03(\v2\x1a.yotta.plugin.v1.PortValueR\aoutputs\x12!\n" +
	"\fexec_outputs\x18\x03 \x03(\tR\vexecOutputs\x122\n" +
	"\afailure\x18\x04 \x01(\v2\x18.yotta.plugin.v1.FailureR\afailure\x121\n" +
	"\x14termination_strength\x18\x05 \x01(\tR\x13terminationStrength\"O\n" +
	"\aFailure\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\" \n" +
	"\x06Cancel\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"R\n" +
	"\x12HostEntropyRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"byte_count\x18\x02 \x01(\rR\tbyteCount\"\x82\x01\n" +
	"\x13HostEntropyResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\aentropy\x18\x02 \x01(\fR\aentropy\x122\n" +
	"\afailure\x18\x03 \x01(\v2\x18.yotta.plugin.v1.FailureR\afailure\"Y\n" +
	"\x0fHostWaitRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0fduration_millis\x18\x02 \x01(\x04R\x0edurationMillis\"e\n" +
	"\x10HostWaitResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x122\n" +
	"\afailure\x18\x02 \x01(\v2\x18.yotta.plugin.v1.FailureR\afailure\"N\n" +
	"\x10StateReadRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\taccess_id\x18\x02 \x01(\tR\baccessId\"\xd9\x01\n" +
	"\x11StateReadResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0evalue_envelope\x18\x02 \x01(\fR\rvalueEnvelope\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\x12.\n" +
	"\x13changed_unix_millis\x18\x04 \x01(\x03R\x11changedUnixMillis\x122\n" +
	"\afailure\x18\x05 \x01(\v2\x18.yotta.plugin.v1.FailureR\afailure\"v\n" +
	"\x11StateWriteRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\taccess_id\x18\x02 \x01(\tR\baccessId\x12%\n" +
	"\x0evalue_envelope\x18\x03 \x01(\fR\rvalueEnvelope\"\xda\x01\n" +
	"\x12StateWriteResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0evalue_envelope\x18\x02 \x01(\fR\rvalueEnvelope\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\x12.\n" +
	"\x13changed_unix_millis\x18\x04 \x01(\x03R\x11changedUnixMillis\x122\n" +
	"\afailure\x18\x05 \x01(\v2\x18.yotta.plugin.v1.FailureR\afailure\"\x81\x02\n" +
	"\vActionEvent\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\tR\beffectId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12!\n" +
	"\fsummary_code\x18\x05 \x01(\tR\vsummaryCode\x124\n" +
	"\bcounters\x18\x06 \x03(\v2\x18.yotta.plugin.v1.CounterR\bcounters\x12+\n" +
	"\x05facts\x18\a \x03(\v2\x15.yotta.plugin.v1.FactR\x05facts\".\n" +
	"\x04Fact\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value*M\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11OUTCOME_SUCCEEDED\x10\x01\x12\x12\n" +
	"\x0eOUTCOME_FAILED\x10\x02BBZ@github.com/yottaapp/yotta/internal/pluginprotocol;pluginprotocolb\x06proto3"

var (
	file_contracts_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_contracts_plugin_v1_plugin_proto_rawDescData []byte
)

func file_contracts_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_contracts_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_contracts_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_plugin_v1_plugin_proto_rawDesc), len(file_contracts_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_contracts_plugin_v1_plugin_proto_rawDescData
}

var file_contracts_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contracts_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_contracts_plugin_v1_plugin_proto_goTypes = []any{
	(Outcome)(0),                // 0: yotta.plugin.v1.Outcome
	(*Frame)(nil),               // 1: yotta.plugin.v1.Frame
	(*Invocation)(nil),          // 2: yotta.plugin.v1.Invocation
	(*PortValue)(nil),           // 3: yotta.plugin.v1.PortValue
	(*Trigger)(nil),             // 4: yotta.plugin.v1.Trigger
	(*Budget)(nil),              // 5: yotta.plugin.v1.Budget
	(*HostOpenRequest)(nil),     // 6: yotta.plugin.v1.HostOpenRequest
	(*HostOpenResponse)(nil),    // 7: yotta.plugin.v1.HostOpenResponse
	(*HostInvokeRequest)(nil),   // 8: yotta.plugin.v1.HostInvokeRequest
	(*HostInvokeResponse)(nil),  // 9: yotta.plugin.v1.HostInvokeResponse
	(*HostDropRequest)(nil),     // 10: yotta.plugin.v1.HostDropRequest
	(*HostDropResponse)(nil),    // 11: yotta.plugin.v1.HostDropResponse
	(*StatusEvent)(nil),         // 12: yotta.plugin.v1.StatusEvent
	(*Counter)(nil),             // 13: yotta.plugin.v1.Counter
	(*Result)(nil),              // 14: yotta.plugin.v1.Result
	(*Failure)(nil),             // 15: yotta.plugin.v1.Failure
	(*Cancel)(nil),              // 16: yotta.plugin.v1.Cancel
	(*HostEntropyRequest)(nil),  // 17: yotta.plugin.v1.HostEntropyRequest
	(*HostEntropyResponse)(nil), // 18: yotta.plugin.v1.HostEntropyResponse
	(*HostWaitRequest)(nil),     // 19: yotta.plugin.v1.HostWaitRequest
	(*HostWaitResponse)(nil),    // 20: yotta.plugin.v1.HostWaitResponse
	(*StateReadRequest)(nil),    // 21: yotta.plugin.v1.StateReadRequest
	(*StateReadResponse)(nil),   // 22: yotta.plugin.v1.StateReadResponse
	(*StateWriteRequest)(nil),   // 23: yotta.plugin.v1.StateWriteRequest
	(*StateWriteResponse)(nil),  // 24: yotta.plugin.v1.StateWriteResponse
	(*ActionEvent)(nil),         // 25: yotta.plugin.v1.ActionEvent
	(*Fact)(nil),                // 26: yotta.plugin.v1.Fact
}
var file_contracts_plugin_v1_plugin_proto_depIdxs = []int32{
	2,  // 0: yotta.plugin.v1.Frame.invocation:type_name -> yotta.plugin.v1.Invocation
	6,  // 1: yotta.plugin.v1.Frame.host_open_request:type_name -> yotta.plugin.v1.HostOpenRequest
	7,  // 2: yotta.plugin.v1.Frame.host_open_response:type_name -> yotta.plugin.v1.HostOpenResponse
	8,  // 3: yotta.plugin.v1.Frame.host_invoke_request:type_name -> yotta.plugin.v1.HostInvokeRequest
	9,  // 4: yotta.plugin.v1.Frame.host_invoke_response:type_name -> yotta.plugin.v1.HostInvokeResponse
	10, // 5: yotta.plugin.v1.Frame.host_drop_request:type_name -> yotta.plugin.v1.HostDropRequest
	11, // 6: yotta.plugin.v1.Frame.host_drop_response:type_name -> yotta.plugin.v1.HostDropResponse
	12, // 7: yotta.plugin.v1.Frame.status:type_name -> yotta.plugin.v1.StatusEvent
	14, // 8: yotta.plugin.v1.Frame.result:type_name -> yotta.plugin.v1.Result
	16, // 9: yotta.plugin.v1.Frame.cancel:type_name -> yotta.plugin.v1.Cancel
	17, // 10: yotta.plugin.v1.Frame.host_entropy_request:type_name -> yotta.plugin.v1.HostEntropyRequest
	18, // 11: yotta.plugin.v1.Frame.host_entropy_response:type_name -> yotta.plugin.v1.HostEntropyResponse
	19, // 12: yotta.plugin.v1.Frame.host_wait_request:type_name -> yotta.plugin.v1.HostWaitRequest
	20, // 13: yotta.plugin.v1.Frame.host_wait_response:type_name -> yotta.plugin.v1.HostWaitResponse
	21, // 14: yotta.plugin.v1.Frame.state_read_request:type_name -> yotta.plugin.v1.StateReadRequest
	22, // 15: yotta.plugin.v1.Frame.state_read_response:type_name -> yotta.plugin.v1.StateReadResponse
	23, // 16: yotta.plugin.v1.Frame.state_write_request:type_name -> yotta.plugin.v1.StateWriteRequest
	24, // 17: yotta.plugin.v1.Frame.state_write_response:type_name -> yotta.plugin.v1.StateWriteResponse
	25, // 18: yotta.plugin.v1.Frame.action:type_name -> yotta.plugin.v1.ActionEvent
	3,  // 19: yotta.plugin.v1.Invocation.inputs:type_name -> yotta.plugin.v1.PortValue
	4,  // 20: yotta.plugin.v1.Invocation.trigger:type_name -> yotta.plugin.v1.Trigger
	5,  // 21: yotta.plugin.v1.Invocation.budget:type_name -> yotta.plugin.v1.Budget
	15, // 22: yotta.plugin.v1.HostOpenResponse.failure:type_name -> yotta.plugin.v1.Failure
	15, // 23: yotta.plugin.v1.HostInvokeResponse.failure:type_name -> yotta.plugin.v1.Failure
	15, // 24: yotta.plugin.v1.HostDropResponse.failure:type_name -> yotta.plugin.v1.Failure
	13, // 25: yotta.plugin.v1.StatusEvent.counters:type_name -> yotta.plugin.v1.Counter
	0,  // 26: yotta.plugin.v1.Result.outcome:type_name -> yotta.plugin.v1.Outcome
	3,  // 27: yotta.plugin.v1.Result.outputs:type_name -> yotta.plugin.v1.PortValue
	15, // 28: yotta.plugin.v1.Result.failure:type_name -> yotta.plugin.v1.Failure
	15, // 29: yotta.plugin.v1.HostEntropyResponse.failure:type_name -> yotta.plugin.v1.Failure
	15, // 30: yotta.plugin.v1.HostWaitResponse.failure:type_name -> yotta.plugin.v1.Failure
	15, // 31: yotta.plugin.v1.StateReadResponse.failure:type_name -> yotta.plugin.v1.Failure
	15, // 32: yotta.plugin.v1.StateWriteResponse.failure:type_name -> yotta.plugin.v1.Failure
	13, // 33: yotta.plugin.v1.ActionEvent.counters:type_name -> yotta.plugin.v1.Counter
	26, // 34: yotta.plugin.v1.ActionEvent.facts:type_name -> yotta.plugin.v1.Fact
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_contracts_plugin_v1_plugin_proto_init() }
func file_contracts_plugin_v1_plugin_proto_init() {
	if File_contracts_plugin_v1_plugin_proto != nil {
		return
	}
	file_contracts_plugin_v1_plugin_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Invocation)(nil),
		(*Frame_HostOpenRequest)(nil),
		(*Frame_HostOpenResponse)(nil),
		(*Frame_HostInvokeRequest)(nil),
		(*Frame_HostInvokeResponse)(nil),
		(*Frame_HostDropRequest)(nil),
		(*Frame_HostDropResponse)(nil),
		(*Frame_Status)(nil),
		(*Frame_Result)(nil),
		(*Frame_Cancel)(nil),
		(*Frame_HostEntropyRequest)(nil),
		(*Frame_HostEntropyResponse)(nil),
		(*Frame_HostWaitRequest)(nil),
		(*Frame_HostWaitResponse)(nil),
		(*Frame_StateReadRequest)(nil),
		(*Frame_StateReadResponse)(nil),
		(*Frame_StateWriteRequest)(nil),
		(*Frame_StateWriteResponse)(nil),
		(*Frame_Action)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_plugin_v1_plugin_proto_rawDesc), len(file_contracts_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_contracts_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_contracts_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_contracts_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_contracts_plugin_v1_plugin_proto = out.File
	file_contracts_plugin_v1_plugin_proto_goTypes = nil
	file_contracts_plugin_v1_plugin_proto_depIdxs = nil
}
